### ISSUE TITLE
Add phpunit/phpunit to require-dev

### ISSUE THREAD

**Issue by elazar** [icecave/duct#9]
This repo currently assumes an available installation of PHPUnit, presumably either via PEAR or manually with PHP configured to add it to `include_path`. Adding it to the `require-dev` section of `composer.json` would remove this assumption and allow tests to be run more easily.

Related diff:

``` diff
diff --git a/composer.json b/composer.json
index 61eb4f3..1fb67cb 100644
--- a/composer.json
+++ b/composer.json
@@ -25,7 +25,8 @@
         "evenement/evenement": "~1"
     },
     "require-dev": {
-        "icecave/archer": "~1"
+        "icecave/archer": "~1",
+        "phpunit/phpunit": "~4"
     },
     "autoload": {
         "psr-4": {
```

Running tests relative to the root of the repository can then be done like so:

```
./vendor/bin/phpunit test/suite
```

**Comment by jmalloc** [comment]
This is *finally* done. How embarrassing.
